version: '3.0'
services:
  ui:
    container_name: react
    build: .
    restart: always
    ports:
      - 9000:3000
    stdin_open: true
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /node_modules
