version: '3.0'
services:
  ui:
    container_name: react
    build: .
    restart: always
    ports:
      - 9000:3000
#    environment:
#      - CHOKIDAR_USEPOLLING=true
#      - NODE_OPTIONS=--openssl-legacy-provider
    stdin_open: true
    volumes:
      - ./src:/app/src
      - ./public:/app/public
#      - /app/node_modules
      - /node_modules
